### ISSUE TITLE
Crash: width and height must be > 0 (v0.2.1)

### ISSUE THREAD

**Issue by tomblenz** [simplifycom/ink-android#11] opened 2016-09-25 19:32 UTC
Every so often I'll get this crash from prod in one of my apps:

```
java.lang.IllegalArgumentException: width and height must be > 0
    at android.graphics.Bitmap.createBitmap(Bitmap.java:939)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:918)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:885)
    at com.simplify.ink.InkView.clear(InkView.java:377)
    at com.simplify.ink.InkView.onSizeChanged(InkView.java:160)
    at android.view.View.sizeChange(View.java:16876)
    at android.view.View.setFrame(View.java:16849)
    at android.view.View.layout(View.java:16764)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
     ...
```

The stack trace is pretty straight forward to follow.  The exception appears to be occurring during a layout pass.  I'm not doing anything crazy - the InkView is defined in an XML layout.  It actually has a specified height (199dp) so it's the width that must be 0 (match parent).  

I'm not sure what the circumstances of this are; maybe the activity is being minimised as a layout pass is occuring?  

A fix may be to simply wrap bitmap creation with a size check.

edit: While you're there... 
`mDebugBitmap = Bitmap.createBitmap(getWidth(), getHeight(), Bitmap.Config.ARGB_8888);`
This line almost doubles the memory footprint of the view; it should probably only be instantiated  when debug is enabled.

**Comment by nak5ive** [comment] 2016-09-26 19:41
Since something is triggering the onSizeChange callback, can you shed a little more light on the behavior of the screen it's embedded in? Does it support orientation change? Are you animating the views in/out/otherwise?

**Comment by nak5ive** [comment] 2016-09-26 19:42
Also, the debug flag/feature has been used minimally at this point, so it's likely to get removed entirely.

**Comment by tomblenz** [comment] 2016-09-26 20:14
Sorry, I literally have no idea how it occurs.  The orientation is locked to landscape.  The activity hosts a fragment within a FrameLayout, the fragment is a scrollview containing a LinearLayout which contains the InkView.  The scrolling content is never large enough to fully obscure the InkView, it is always visible.

Android Views should certainly be able to handle a size of 0,0.  Knowing the superficial cause of how it got to be 0,0 would be interesting for sure, I wouldn't be surprised if it's a timing thing or a quirk of Android (or the tablet this app runs on, Samsung Tab A).  But once the root cause is fixed it would be moot.

**Comment by nak5ive** [comment] 2016-09-27 14:38
I've been unable to reproduce the issue, and without much visibility into what's causing the issue, I can't go much further. I'm going to close this issue.

I will be pushing a new build that deprecates the debug flag and removes that memory overhead, however, so not all is lost :)

**Closed as completed by nak5ive** 2016-09-27 14:38 UTC

**Comment by ZaidMirza** [comment] 2018-06-10 08:39
Im facing same problem. Size changes when keyboard opens via clicking edit text

**Comment by ZaidMirza** [comment] 2018-06-10 08:49
android:windowSoftInputMode="adjustPan" putting this in activity solves the problem
